sudo: required
dist: trusty
services:
  - docker
language: node_js
node_js:
  - 6
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - npm install
script:
  - sh build_docker.sh
# after_success:
#   - npm run exec:coveralls
