#copay-builder
FROM node:7.10.0

LABEL description="Copay builder image"
LABEL version="3.6.0"
LABEL maintainer "peter@froggle.org"

RUN npm install -g git

# create work directory
RUN mkdir /src
COPY . /src
WORKDIR /src

RUN npm run apply:decred
 
# build copay
CMD [ "./webwallet-build.sh" ]
